export const IDLE_STATUS = 'IDLE_STATUS'
export const LOADED_STATUS = 'LOADED_STATUS'
export const INIT_STATUS = 'INIT_STATUS'
export const PENDING_STATUS = 'PENDING_STATUS'
export const FILES_UPLOADED_STATUS = 'FILES_UPLOADED_STATUS'
export const UPLOAD_ERROR_STATUS = 'UPLOAD_ERROR_STATUS'

// Reducer
export const LOAD_ACTION = 'LOAD_ACTION'
export const SUBMIT_ACTION = 'SUBMIT_ACTION'
export const NEXT_ACTION = 'NEXT_ACTION'
export const FILE_UPLOADED_ACTION = 'FILE_UPLOADED_ACTION'
export const FILES_UPLOADED_ACTION = 'FILES_UPLOADED_ACTION'
export const SET_UPLOAD_ERROR = 'SET_UPLOAD_ERROR'